trigger:
  branches:
    include:
    - main
  paths:
    include:
    - build_pipeline.yml
    exclude:
    - Readme.md

resources:
- repo: self

variables:
  IMAGE_NAME: nginx
  REGISTRY_URL: azure-harbor-registry.cloudsmartz.com
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        repository: $(IMAGE_NAME)
        tags: $(TAG)
    - bash: docker tag $(IMAGE_NAME):$(TAG) ${REGISTRY_URL}/nginx/$(IMAGE_NAME):$(TAG)

    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'harbor-connection'
        repository: nginx/$(IMAGE_NAME)
        command: 'push'
        tags: '$(TAG)'
